#!/usr/bin/env bash
#Install nginx web server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo mkdir /etc/nginx/html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo echo  "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

        server_name _;
}
" > /etc/nginx/sites-available/default
nginx -s reload
